#ifndef __BUTTON_H
#define __BUTTON_H

void ButtonInit();
unsigned short ProcessButtonEvents();
unsigned short GetButtonState();

#define KEYBOARD_BUTTONS 6

//#define FIX_BUG_IN_MAPPING


#if (KEYBOARD_BUTTONS == 16)
#define BUTTON_EXIT 0x0008
#define BUTTON_DOWN 0x0004
#define BUTTON_UP 	0x0002
#define BUTTON_ENTER 0x0001

#define BUTTON_SEARCH	0x0010
#define BUTTON_LOCATE   0x0020
#define BUTTON_SETTINGS	0x0040
#define BUTTON_LOG 		0x0080

#define BUTTON_PAUSE	0x0100
#define BUTTON_TEST 	0x0200
#define BUTTON_SPARE2 	0x0400
#define BUTTON_QUICK_SEARCH 	0x0800

#define BEEPABLE_BUTTONS (BUTTON_EXIT | BUTTON_DOWN | BUTTON_UP | BUTTON_ENTER | BUTTON_SEARCH | BUTTON_LOCATE | BUTTON_SETTINGS | BUTTON_PAUSE | BUTTON_LOG | BUTTON_QUICK_SEARCH | BUTTON_TEST)

#elif (KEYBOARD_BUTTONS == 6)

#ifdef FIX_BUG_IN_MAPPING
#define BUTTON_ENTER 	0x0040
#define BUTTON_F1 		0x0400
#else
#define BUTTON_ENTER 	0x0001
#define BUTTON_F1 		0x0002
#define BUTTON_ENTER_2 	0x0040
#define BUTTON_F1_2 	0x0400
#endif

#define BUTTON_DOWN		0x0010
#define BUTTON_UP   	0x0020

#define BUTTON_EXIT		0x0100
#define BUTTON_F2	 	0x0200

#define BEEPABLE_BUTTONS (BUTTON_EXIT | BUTTON_DOWN | BUTTON_UP | BUTTON_ENTER | BUTTON_F1 | BUTTON_F2)

#else
#error KEYBOARD BUTTON SIZE NOT DEFINED
#endif

#define BUTTON_REFRESH_PERIOD_MS	200

#endif // __BUTTON_H

